% Chapter9_Lesson3_Simulink.m
% Programmatic Simulink model that streams poses and measurements from workspace,
% updates a landmark map using a MATLAB Function block, and logs the map output.
%
% This script CREATES the model "Chapter9_Lesson3_Simulink.slx" in the current folder.
% Run this file, then open the generated model.

clear; clc;
rng(7);

model = 'Chapter9_Lesson3_Simulink';
if bdIsLoaded(model), close_system(model,0); end
new_system(model);
open_system(model);

% ---- Prepare workspace signals ----
wrap = @(a) mod(a+pi,2*pi)-pi;
T = 120;
t = linspace(0, 2*pi, T).';
px = 2.5*cos(t) + 0.5*cos(3*t);
py = 2.0*sin(t);
th = wrap(atan2(gradient(py), gradient(px)));
X = [t, px, py, th];  % time series for poses

% a simple synthetic measurement stream: (range,bearing) to one landmark
mtrue = [-2, -4];
zr = hypot(mtrue(1)-px, mtrue(2)-py) + 0.15*randn(T,1);
zb = wrap(atan2(mtrue(2)-py, mtrue(1)-px) - th + deg2rad(2)*randn(T,1));
Z = [t, zr, zb];

assignin('base','X_ts', timeseries(X(:,2:4), X(:,1)));
assignin('base','Z_ts', timeseries(Z(:,2:3), Z(:,1)));

% ---- Build blocks ----
set_param(model,'StopTime',num2str(t(end)));

add_block('simulink/Sources/From Workspace',[model '/Pose From WS'], ...
    'VariableName','X_ts','Position',[50 60 170 110]);

add_block('simulink/Sources/From Workspace',[model '/Meas From WS'], ...
    'VariableName','Z_ts','Position',[50 160 170 210]);

% MATLAB Function block (single-landmark EKF update)
add_block('simulink/User-Defined Functions/MATLAB Function',[model '/Landmark EKF'], ...
    'Position',[260 90 430 200]);

% To Workspace for logging
add_block('simulink/Sinks/To Workspace',[model '/Map To WS'], ...
    'VariableName','map_out','SaveFormat','Array', ...
    'Position',[500 120 620 170]);

% Connect
add_line(model,'Pose From WS/1','Landmark EKF/1');
add_line(model,'Meas From WS/1','Landmark EKF/2');
add_line(model,'Landmark EKF/1','Map To WS/1');

% ---- Fill MATLAB Function code ----
code = [
"function y = fcn(x, z)", newline, ...
"% x = [px; py; th], z = [r; b]", newline, ...
"persistent mu P initialized", newline, ...
"if isempty(initialized)", newline, ...
"  initialized = false;", newline, ...
"  mu = [0;0];", newline, ...
"  P = eye(2)*(1.5^2);", newline, ...
"end", newline, ...
"wrap = @(a) mod(a+pi,2*pi)-pi;", newline, ...
"sigma_r = 0.15; sigma_b = deg2rad(2);", newline, ...
"R = diag([sigma_r^2, sigma_b^2]);", newline, ...
"", newline, ...
"if ~initialized", newline, ...
"  % initialize landmark by inverse model", newline, ...
"  ang = x(3) + z(2);", newline, ...
"  mu = [x(1) + z(1)*cos(ang); x(2) + z(1)*sin(ang)];", newline, ...
"  initialized = true;", newline, ...
"else", newline, ...
"  % EKF measurement update", newline, ...
"  dx = mu(1)-x(1); dy = mu(2)-x(2);", newline, ...
"  q = dx^2 + dy^2; rhat = sqrt(q);", newline, ...
"  bhat = wrap(atan2(dy,dx) - x(3));", newline, ...
"  yinnov = [z(1)-rhat; wrap(z(2)-bhat)];", newline, ...
"  H = [dx/rhat, dy/rhat; -dy/q, dx/q];", newline, ...
"  S = H*P*H' + R;", newline, ...
"  K = P*H'/S;", newline, ...
"  mu = mu + K*yinnov;", newline, ...
"  P = (eye(2)-K*H)*P;", newline, ...
"  P = 0.5*(P+P');", newline, ...
"end", newline, ...
"", newline, ...
"% output [mx; my] for logging", newline, ...
"y = mu;", newline
];

set_param([model '/Landmark EKF'], 'Script', code);

save_system(model);
disp(['Created model: ' model '.slx']);
