// Chapter19_Lesson5.java
import java.io.*; import java.util.*;
public class Chapter19_Lesson5 {
  static class R {String s; int seed,succ,col; double t,pl,sp,clr,en,ate,rpe,cm,cp;}
  static List<R> readCsv(String p) throws Exception { var out=new ArrayList<R>(); try(var br=new BufferedReader(new FileReader(p))){ String line=br.readLine(); while((line=br.readLine())!=null){ if(line.isBlank()) continue; var t=line.split(","); if(t.length<13) continue; R r=new R(); r.s=t[0]; r.seed=Integer.parseInt(t[1]); r.succ=Integer.parseInt(t[2]); r.t=Double.parseDouble(t[3]); r.pl=Double.parseDouble(t[4]); r.sp=Double.parseDouble(t[5]); r.col=Integer.parseInt(t[6]); r.clr=Double.parseDouble(t[7]); r.en=Double.parseDouble(t[8]); r.ate=Double.parseDouble(t[9]); r.rpe=Double.parseDouble(t[10]); r.cm=Double.parseDouble(t[11]); r.cp=Double.parseDouble(t[12]); out.add(r);} } return out; }
  static double mean(List<Double>x){ double s=0; for(double v:x)s+=v; return s/x.size(); }
  static double q(List<Double>x,double p){ x=new ArrayList<>(x); Collections.sort(x); double k=(x.size()-1)*p; int i=(int)Math.floor(k), j=(int)Math.ceil(k); return i==j?x.get(i):x.get(i)*(j-k)+x.get(j)*(k-i); }
  static void agg(String name,List<R> rs){ var succ=new ArrayList<Double>(); var spl=new ArrayList<Double>(); var col=new ArrayList<Double>(); var t=new ArrayList<Double>(); var ate=new ArrayList<Double>(); var rpe=new ArrayList<Double>(); var clr=new ArrayList<Double>(); var eper=new ArrayList<Double>(); var cm=new ArrayList<Double>(); var cp=new ArrayList<Double>(); for(R r:rs){ succ.add((double)r.succ); spl.add(r.succ==1? r.sp/Math.max(r.pl,1e-9):0.0); col.add(r.col>0?1.0:0.0); t.add(r.t); ate.add(r.ate); rpe.add(r.rpe); clr.add(r.clr); eper.add(r.en/Math.max(r.pl,1e-9)); cm.add(r.cm); cp.add(r.cp);} System.out.printf(Locale.US,"%s: success=%.4f SPL=%.4f collision=%.4f time=%.3f ATE=%.4f RPE=%.4f clrP10=%.4f E/m=%.2f CPU=%.2f p95=%.2f%n",name,mean(succ),mean(spl),mean(col),mean(t),mean(ate),mean(rpe),q(clr,0.1),mean(eper),mean(cm),mean(cp)); }
  public static void main(String[] args) throws Exception { if(args.length<2){ System.err.println("Usage: java Chapter19_Lesson5 baseline.csv candidate.csv"); return; } agg("Baseline", readCsv(args[0])); agg("Candidate", readCsv(args[1])); }
}
