// Chapter15_Lesson2.java
// Output Energy Generated by Initial States
// From-scratch RK4 integration; no external Java libraries required.
// Compile: javac Chapter15_Lesson2.java
// Run:     java Chapter15_Lesson2

public class Chapter15_Lesson2 {
    static final int N = 3;
    static final int P = 2;

    static double[][] zeros() {
        return new double[N][N];
    }

    static double[][] transpose(double[][] A) {
        double[][] T = zeros();
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                T[i][j] = A[j][i];
        return T;
    }

    static double[][] add(double[][] A, double[][] B) {
        double[][] R = zeros();
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                R[i][j] = A[i][j] + B[i][j];
        return R;
    }

    static double[][] scale(double[][] A, double s) {
        double[][] R = zeros();
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                R[i][j] = s * A[i][j];
        return R;
    }

    static double[][] multiply(double[][] A, double[][] B) {
        double[][] R = zeros();
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                for (int k = 0; k < N; k++)
                    R[i][j] += A[i][k] * B[k][j];
        return R;
    }

    static double[] matvec(double[][] A, double[] x) {
        double[] y = new double[N];
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                y[i] += A[i][j] * x[j];
        return y;
    }

    static double[][] ctC(double[][] C) {
        double[][] Q = zeros();
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                for (int r = 0; r < P; r++)
                    Q[i][j] += C[r][i] * C[r][j];
        return Q;
    }

    static double[][] rhsW(double[][] A, double[][] Q, double[][] W) {
        return add(add(multiply(transpose(A), W), multiply(W, A)), Q);
    }

    static double[][] rk4W(double[][] A, double[][] Q, double[][] W, double h) {
        double[][] k1 = rhsW(A, Q, W);
        double[][] k2 = rhsW(A, Q, add(W, scale(k1, 0.5 * h)));
        double[][] k3 = rhsW(A, Q, add(W, scale(k2, 0.5 * h)));
        double[][] k4 = rhsW(A, Q, add(W, scale(k3, h)));
        return add(W, scale(add(add(k1, scale(k2, 2.0)), add(scale(k3, 2.0), k4)), h / 6.0));
    }

    static double[] rk4X(double[][] A, double[] x, double h) {
        double[] k1 = matvec(A, x);
        double[] x2 = new double[N];
        for (int i = 0; i < N; i++) x2[i] = x[i] + 0.5 * h * k1[i];

        double[] k2 = matvec(A, x2);
        double[] x3 = new double[N];
        for (int i = 0; i < N; i++) x3[i] = x[i] + 0.5 * h * k2[i];

        double[] k3 = matvec(A, x3);
        double[] x4 = new double[N];
        for (int i = 0; i < N; i++) x4[i] = x[i] + h * k3[i];

        double[] k4 = matvec(A, x4);
        double[] xn = new double[N];
        for (int i = 0; i < N; i++)
            xn[i] = x[i] + h * (k1[i] + 2.0 * k2[i] + 2.0 * k3[i] + k4[i]) / 6.0;
        return xn;
    }

    static double density(double[][] C, double[] x) {
        double sum = 0.0;
        for (int r = 0; r < P; r++) {
            double yr = 0.0;
            for (int j = 0; j < N; j++) yr += C[r][j] * x[j];
            sum += yr * yr;
        }
        return sum;
    }

    static double quadratic(double[][] W, double[] x) {
        double[] Wx = matvec(W, x);
        double s = 0.0;
        for (int i = 0; i < N; i++) s += x[i] * Wx[i];
        return s;
    }

    static void printMatrix(double[][] W) {
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < N; j++)
                System.out.printf("%14.8f ", W[i][j]);
            System.out.println();
        }
    }

    public static void main(String[] args) {
        double[][] A = {
            {-1.0,  0.2,  0.0},
            { 0.0, -0.6,  1.0},
            { 0.0, -1.2, -0.8}
        };

        double[][] C = {
            {1.0, 0.0, 0.0},
            {0.0, 0.5, 1.0}
        };

        double[] x0 = {1.0, -0.4, 0.8};
        double T = 5.0;
        int steps = 10000;
        double h = T / steps;

        double[][] Q = ctC(C);
        double[][] W = zeros();
        double[] x = x0.clone();

        double EDirect = 0.0;
        double previous = density(C, x);

        for (int k = 0; k < steps; k++) {
            W = rk4W(A, Q, W, h);
            double[] xNext = rk4X(A, x, h);
            double next = density(C, xNext);
            EDirect += 0.5 * h * (previous + next);
            x = xNext;
            previous = next;
        }

        double EQuad = quadratic(W, x0);
        System.out.println("Finite-horizon observability Gramian W_o(0,T):");
        printMatrix(W);
        System.out.printf("%nEnergy from x0^T W_o x0: %.10f%n", EQuad);
        System.out.printf("Energy from direct output integration: %.10f%n", EDirect);
        System.out.printf("Absolute difference: %.10e%n", Math.abs(EQuad - EDirect));
    }
}
