// Chapter15_Lesson2.cpp
// Output Energy Generated by Initial States
// Requires Eigen: https://eigen.tuxfamily.org
// Compile: g++ -std=c++17 Chapter15_Lesson2.cpp -O2 -I /path/to/eigen -o Chapter15_Lesson2

#include <Eigen/Dense>
#include <iostream>
#include <iomanip>

using Matrix = Eigen::MatrixXd;
using Vector = Eigen::VectorXd;

Matrix gramian_rhs(const Matrix& A, const Matrix& Q, const Matrix& W) {
    return A.transpose() * W + W * A + Q;
}

Matrix rk4_step_gramian(const Matrix& A, const Matrix& Q, const Matrix& W, double h) {
    Matrix k1 = gramian_rhs(A, Q, W);
    Matrix k2 = gramian_rhs(A, Q, W + 0.5 * h * k1);
    Matrix k3 = gramian_rhs(A, Q, W + 0.5 * h * k2);
    Matrix k4 = gramian_rhs(A, Q, W + h * k3);
    return W + (h / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4);
}

Vector rk4_step_state(const Matrix& A, const Vector& x, double h) {
    Vector k1 = A * x;
    Vector k2 = A * (x + 0.5 * h * k1);
    Vector k3 = A * (x + 0.5 * h * k2);
    Vector k4 = A * (x + h * k3);
    return x + (h / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4);
}

double output_density(const Matrix& C, const Vector& x) {
    Vector y = C * x;
    return y.squaredNorm();
}

int main() {
    Matrix A(3, 3);
    A << -1.0,  0.2,  0.0,
          0.0, -0.6,  1.0,
          0.0, -1.2, -0.8;

    Matrix C(2, 3);
    C << 1.0, 0.0, 0.0,
         0.0, 0.5, 1.0;

    Vector x0(3);
    x0 << 1.0, -0.4, 0.8;

    const double T = 5.0;
    const int steps = 10000;
    const double h = T / static_cast<double>(steps);

    Matrix Q = C.transpose() * C;
    Matrix W = Matrix::Zero(3, 3);
    Vector x = x0;

    double E_direct = 0.0;
    double previous = output_density(C, x);

    for (int k = 0; k < steps; ++k) {
        W = rk4_step_gramian(A, Q, W, h);
        Vector x_next = rk4_step_state(A, x, h);
        double next = output_density(C, x_next);
        E_direct += 0.5 * h * (previous + next);
        x = x_next;
        previous = next;
    }

    double E_quad = x0.transpose() * W * x0;

    std::cout << std::fixed << std::setprecision(10);
    std::cout << "Finite-horizon observability Gramian W_o(0,T):\n" << W << "\n\n";
    std::cout << "Energy from x0^T W_o x0: " << E_quad << "\n";
    std::cout << "Energy from direct output integration: " << E_direct << "\n";
    std::cout << "Absolute difference: " << std::abs(E_quad - E_direct) << "\n";

    return 0;
}
