% Chapter15_Lesson2.m
% Output Energy Generated by Initial States
% Requires: Control System Toolbox for lyap, ss, and initial.

clear; clc; close all;

A = [-1.0  0.2  0.0;
      0.0 -0.6  1.0;
      0.0 -1.2 -0.8];

C = [1.0 0.0 0.0;
     0.0 0.5 1.0];

x0 = [1.0; -0.4; 0.8];
T  = 5.0;
Q  = C' * C;
n  = size(A, 1);

% Infinite-horizon observability Gramian:
% A' * W + W * A + C' * C = 0
Wo_inf = lyap(A', Q);
E_inf = x0' * Wo_inf * x0;

% Finite-horizon Gramian from dW/dt = A'W + WA + C'C, W(0)=0.
odefun = @(t,wvec) reshape(A' * reshape(wvec,n,n) + reshape(wvec,n,n) * A + Q, [], 1);
[tW, wsol] = ode45(odefun, [0 T], zeros(n*n, 1));
Wo_T = reshape(wsol(end,:).', n, n);
Wo_T = 0.5 * (Wo_T + Wo_T');

E_T_quad = x0' * Wo_T * x0;

% Simulink-equivalent zero-input initial response.
% A Simulink State-Space block with this A,C and initial state x0 gives the same y(t).
Bdummy = zeros(n, 1);
Ddummy = zeros(size(C, 1), 1);
sys = ss(A, Bdummy, C, Ddummy);

time = linspace(0, T, 1000);
[y, t, x] = initial(sys, x0, time);
E_T_initial = trapz(t, sum(y.^2, 2));

disp('Finite-horizon observability Gramian W_o(0,T):');
disp(Wo_T);
disp('Eigenvalues of W_o(0,T):');
disp(eig(Wo_T).');
fprintf('Energy from x0'' W_o x0: %.12f\n', E_T_quad);
fprintf('Energy from initial-response integration: %.12f\n', E_T_initial);
fprintf('Absolute difference: %.3e\n', abs(E_T_quad - E_T_initial));

disp('Infinite-horizon observability Gramian W_o:');
disp(Wo_inf);
fprintf('Infinite-horizon output energy: %.12f\n', E_inf);

figure;
plot(t, y, 'LineWidth', 1.5);
grid on;
xlabel('Time');
ylabel('Output components');
title('Zero-input output response y(t)=C exp(A t) x_0');
legend('y_1', 'y_2');
