# Chapter15_Lesson2.py
# Output Energy Generated by Initial States
# Requires: numpy, scipy

import numpy as np
from scipy.linalg import expm, solve_continuous_lyapunov, eigvalsh
from scipy.integrate import quad


def finite_observability_gramian(A: np.ndarray, C: np.ndarray, T: float, n_grid: int = 2000) -> np.ndarray:
    """Approximate W_o(0,T)=int_0^T exp(A^T t) C^T C exp(A t) dt."""
    if T <= 0:
        raise ValueError("T must be positive.")
    Q = C.T @ C
    grid = np.linspace(0.0, T, n_grid)
    dt = grid[1] - grid[0]
    W = np.zeros((A.shape[0], A.shape[0]))

    for k, t in enumerate(grid):
        Phi = expm(A * t)
        weight = 0.5 if k == 0 or k == n_grid - 1 else 1.0
        W += weight * (Phi.T @ Q @ Phi)

    return dt * W


def output_energy_by_quadrature(A: np.ndarray, C: np.ndarray, x0: np.ndarray, T: float) -> float:
    """Compute int_0^T ||C exp(A t) x0||_2^2 dt."""
    def integrand(t: float) -> float:
        y = C @ expm(A * t) @ x0
        return float(y.T @ y)

    value, _ = quad(integrand, 0.0, T, epsabs=1e-10, epsrel=1e-10, limit=200)
    return value


def main() -> None:
    A = np.array([
        [-1.0,  0.2,  0.0],
        [ 0.0, -0.6,  1.0],
        [ 0.0, -1.2, -0.8]
    ], dtype=float)

    C = np.array([
        [1.0, 0.0, 0.0],
        [0.0, 0.5, 1.0]
    ], dtype=float)

    x0 = np.array([1.0, -0.4, 0.8], dtype=float)
    T = 5.0

    W_T = finite_observability_gramian(A, C, T)
    E_T_quadratic = float(x0.T @ W_T @ x0)
    E_T_integral = output_energy_by_quadrature(A, C, x0, T)

    # Infinite-horizon Gramian for stable A:
    # A^T W + W A = -C^T C
    W_inf = solve_continuous_lyapunov(A.T, -(C.T @ C))
    E_inf = float(x0.T @ W_inf @ x0)

    print("Finite-horizon observability Gramian W_o(0,T):")
    print(W_T)
    print("\nEigenvalues of W_o(0,T):", eigvalsh(W_T))
    print("\nEnergy from x0^T W_o x0:", E_T_quadratic)
    print("Energy from direct output integration:", E_T_integral)
    print("Absolute difference:", abs(E_T_quadratic - E_T_integral))

    print("\nInfinite-horizon observability Gramian W_o:")
    print(W_inf)
    print("Infinite-horizon output energy:", E_inf)


if __name__ == "__main__":
    main()
