% Chapter1_Lesson4_Simulink.m
% Programmatically builds a Simulink model that mirrors the sensing–estimation–navigation pipeline.
%
% Requires: Simulink. Optional: Robotics System Toolbox (not required).
%
% What you get:
%   Model name: ch1_l4_pipeline.slx
%   Blocks:
%     - Controller (MATLAB Function): go-to-goal based on x_hat
%     - Plant (MATLAB Function): unicycle step producing x_true
%     - Odometry noise and integration (MATLAB Function): produces x_prior
%     - Landmark sensor (MATLAB Function): range-bearing z
%     - Estimator (MATLAB Function): one Gauss-Newton/WLS step -> x_hat
%
% Run:
%   Chapter1_Lesson4_Simulink
%   open_system('ch1_l4_pipeline')

clear; clc;

model = 'ch1_l4_pipeline';
if bdIsLoaded(model)
    close_system(model, 0);
end
new_system(model);
open_system(model);

set_param(model, 'StopTime', '35');      % 35 s
set_param(model, 'FixedStep', '0.1');    % dt = 0.1
set_param(model, 'Solver', 'FixedStepDiscrete');

% Layout helpers
x0 = 50; y0 = 60; dx = 220; dy = 110;
blkW = 150; blkH = 60;

% --- Source: goal (constant) ---
add_block('simulink/Sources/Constant', [model '/Goal'], ...
    'Position', [x0 y0 x0+blkW y0+blkH], ...
    'Value', '[7;7]');

% --- Initial x_hat (Unit Delay) ---
add_block('simulink/Discrete/Unit Delay', [model '/x_hat(z^-1)'], ...
    'Position', [x0 y0+dy x0+blkW y0+dy+blkH], ...
    'InitialCondition', '[0;0;0]');

% --- Controller MATLAB Function ---
add_block('simulink/User-Defined Functions/MATLAB Function', [model '/Controller'], ...
    'Position', [x0+dx y0+dy x0+dx+blkW y0+dy+blkH]);

set_param([model '/Controller'], 'Script', sprintf([ ...
'function u = f(goal, xhat)\n' ...
'%% go-to-goal controller using estimate\n' ...
'%% xhat = [x;y;th], u = [v;w]\n' ...
'kHeading = 1.6; vMax = 0.9;\n' ...
'dx = goal(1) - xhat(1);\n' ...
'dy = goal(2) - xhat(2);\n' ...
'dist = hypot(dx,dy);\n' ...
'desired = atan2(dy,dx);\n' ...
'headingErr = wrapToPi(desired - xhat(3));\n' ...
'v = vMax * tanh(dist);\n' ...
'w = kHeading * headingErr;\n' ...
'u = [v;w];\n' ...
'end\n' ...
])));

% --- Plant MATLAB Function (true dynamics) ---
add_block('simulink/User-Defined Functions/MATLAB Function', [model '/Plant'], ...
    'Position', [x0+2*dx y0+dy x0+2*dx+blkW y0+dy+blkH]);

set_param([model '/Plant'], 'Script', sprintf([ ...
'function xtrue = f(xtrue_prev, u)\n' ...
'%% unicycle discrete dynamics, dt = 0.1 assumed\n' ...
'dt = 0.1;\n' ...
'v = u(1); w = u(2);\n' ...
'th = xtrue_prev(3);\n' ...
'x = xtrue_prev(1) + v*dt*cos(th);\n' ...
'y = xtrue_prev(2) + v*dt*sin(th);\n' ...
'th = wrapToPi(xtrue_prev(3) + w*dt);\n' ...
'xtrue = [x;y;th];\n' ...
'end\n' ...
])));

% --- True state memory (Unit Delay) ---
add_block('simulink/Discrete/Unit Delay', [model '/x_true(z^-1)'], ...
    'Position', [x0+2*dx y0 x0+2*dx+blkW y0+blkH], ...
    'InitialCondition', '[0;0;0]');

% --- Odometry + Prior (MATLAB Function) ---
add_block('simulink/User-Defined Functions/MATLAB Function', [model '/OdometryPrior'], ...
    'Position', [x0+2*dx y0+2*dy x0+2*dx+blkW y0+2*dy+blkH]);

set_param([model '/OdometryPrior'], 'Script', sprintf([ ...
'function xprior = f(xhat_prev, u)\n' ...
'%% noisy odometry integration, dt=0.1 assumed\n' ...
'dt = 0.1;\n' ...
'sigmaV = 0.08; sigmaW = deg2rad(3);\n' ...
'v = u(1) + sigmaV*randn;\n' ...
'w = u(2) + sigmaW*randn;\n' ...
'th = xhat_prev(3);\n' ...
'x = xhat_prev(1) + v*dt*cos(th);\n' ...
'y = xhat_prev(2) + v*dt*sin(th);\n' ...
'th = wrapToPi(xhat_prev(3) + w*dt);\n' ...
'xprior = [x;y;th];\n' ...
'end\n' ...
])));

% --- Sensor (range-bearing to one landmark for simplicity) ---
add_block('simulink/User-Defined Functions/MATLAB Function', [model '/LandmarkSensor'], ...
    'Position', [x0+3*dx y0 x0+3*dx+blkW y0+blkH]);

set_param([model '/LandmarkSensor'], 'Script', sprintf([ ...
'function z = f(xtrue)\n' ...
'%% range-bearing to a single known landmark, with noise\n' ...
'lm = [6;6];\n' ...
'sigmaR = 0.12; sigmaB = deg2rad(2);\n' ...
'dx = lm(1) - xtrue(1);\n' ...
'dy = lm(2) - xtrue(2);\n' ...
'r = hypot(dx,dy);\n' ...
'b = wrapToPi(atan2(dy,dx) - xtrue(3));\n' ...
'z = [r + sigmaR*randn; wrapToPi(b + sigmaB*randn)];\n' ...
'end\n' ...
])));

% --- Estimator (one WLS/GN step) ---
add_block('simulink/User-Defined Functions/MATLAB Function', [model '/Estimator'], ...
    'Position', [x0+3*dx y0+dy x0+3*dx+blkW y0+dy+blkH]);

set_param([model '/Estimator'], 'Script', sprintf([ ...
'function xhat = f(xprior, z)\n' ...
'%% one Gauss-Newton step for pose from a single landmark range-bearing\n' ...
'lm = [6;6];\n' ...
'sigmaR = 0.12; sigmaB = deg2rad(2);\n' ...
'R = diag([sigmaR^2, sigmaB^2]);\n' ...
'\n' ...
'x = xprior; %% linearize at prior\n' ...
'dx = lm(1) - x(1);\n' ...
'dy = lm(2) - x(2);\n' ...
'q = max(dx^2 + dy^2, 1e-12);\n' ...
'rhat = sqrt(q);\n' ...
'bhat = wrapToPi(atan2(dy,dx) - x(3));\n' ...
'res = [z(1)-rhat; wrapToPi(z(2)-bhat)];\n' ...
'\n' ...
'H = [-dx/rhat, -dy/rhat, 0;\n' ...
'      dy/q,    -dx/q,  -1];\n' ...
'\n' ...
'%% simple diagonal prior weight (tunable)\n' ...
'P = diag([0.15^2, 0.15^2, deg2rad(8)^2]);\n' ...
'A = inv(P) + H''/R*H;\n' ...
'b = H''/R*res;\n' ...
'delta = A\\b;\n' ...
'xhat = x + delta;\n' ...
'xhat(3) = wrapToPi(xhat(3));\n' ...
'end\n' ...
])));

% --- Scope blocks ---
add_block('simulink/Sinks/Scope', [model '/Scope'], ...
    'Position', [x0+4*dx y0+dy x0+4*dx+blkW y0+dy+blkH]);
set_param([model '/Scope'], 'NumInputPorts', '2');

% --- Wiring ---
add_line(model, 'Goal/1', 'Controller/1');
add_line(model, 'x_hat(z^-1)/1', 'Controller/2');

add_line(model, 'Controller/1', 'Plant/2');
add_line(model, 'x_true(z^-1)/1', 'Plant/1');

add_line(model, 'Plant/1', 'x_true(z^-1)/1'); % feedback state

add_line(model, 'Controller/1', 'OdometryPrior/2');
add_line(model, 'x_hat(z^-1)/1', 'OdometryPrior/1');

add_line(model, 'x_true(z^-1)/1', 'LandmarkSensor/1');

add_line(model, 'OdometryPrior/1', 'Estimator/1');
add_line(model, 'LandmarkSensor/1', 'Estimator/2');

add_line(model, 'Estimator/1', 'x_hat(z^-1)/1'); % update estimate

add_line(model, 'x_true(z^-1)/1', 'Scope/1');
add_line(model, 'x_hat(z^-1)/1', 'Scope/2');

save_system(model);
disp('Built and saved ch1_l4_pipeline.slx');
